Page({
    data: {
        selectedIndex:0,
        cities:[
            {
                name:'热门',
                list:[
                {
                    rname:'北京',
                    img:'',
                },
                {
                    rname:'香港',
                    img:'',
                },
                {
                    rname:'上海',
                    img:'',
                },
                {
                    rname:'厦门',
                    img:'',
                },
                {
                    rname:'三亚',
                    img:'',
                },
                {
                    rname:'成都',
                    img:'',
                },
                {
                    rname:'丽江',
                    img:'',
                },
                {
                    rname:'西安',
                    img:'',
                },
                {
                    rname:'重庆',
                    img:'',
                },
                {
                    rname:'杭州',
                    img:'',
                },
                ]
            },
            {
                name:'安徽',
                img:{},
            },
            {
                name:'北京',
                img:{},
            },
            {
                name:'重庆',
                img:{},
            },
            {
                name:'福建',
                img:{},
            },
            {
                name:'甘肃',
                img:{},
            },
            {
                name:'广东',
                img:{},
            },
            {
                name:'广西',
                img:{},
            },
            {
                name:'贵州',
                img:{},
            },
            {
                name:'黑龙江',
                img:{},
            },
            {
                name:'河南',
                img:{},
            },
            {
                name:'海南',
                img:{},
            },
            {
                name:'湖南',
                img:{},
            },
            {
                name:'河北',
                img:{},
            },
            {
                name:'湖北',
                img:{},
            },
            {
                name:'江西',
                img:{},
            },
            {
                name:'江苏',
                img:{},
            },
            {
                name:'吉林',
                img:{},
            },
            {
                name:'辽宁',
                img:{},
            },
            {
                name:'内蒙',
                img:{},
            },
            {
                name:'宁夏',
                img:{},
            },
            {
                name:'青海',
                img:{},
            },
            {
                name:'山东',
                img:{},
            },
            {
                name:'上海',
                img:{},
            },
            {
                name:'陕西',
                img:{},
            },
            {
                name:'山西',
                img:{},
            },
            {
                name:'四川',
                img:{},
            },
            {
                name:'天津',
                img:{},
            },
            {
                name:'新疆',
                img:{},
            },
            {
                name:'云南',
                img:{},
            },
            {
                name:'浙江',
                img:{},
            },
        ]
    },
    selected(e){
        console.log(e.currentTarget.dataset.index)
        this.setData({
            selectedIndex:e.currentTarget.dataset.index
        })
    },
    onLoad: function () {
        // 监听页面加载的生命周期函数
    },
    onReady: function() {
        // 监听页面初次渲染完成的生命周期函数
    },
    onShow: function() {
        // 监听页面显示的生命周期函数
        // console.log(this.getData('selectedIndex'))
    },
    onHide: function() {
        // 监听页面隐藏的生命周期函数
    },
    onUnload: function() {
        // 监听页面卸载的生命周期函数
    },
    onPullDownRefresh: function() {
        // 监听用户下拉动作
    },
    onReachBottom: function() {
        // 页面上拉触底事件的处理函数
    },
    onShareAppMessage: function () {
        // 用户点击右上角转发
    },
});